App.prototype.nations = [
	 'Kenya' , 
	 'Afghanistan' , 
	 'Albania' , 
	 'Algeria' , 
	 'American Samoa' , 
	 'Andorra' , 
	 'Angola' , 
	 'Anguilla' , 
	 'Antarctica' , 
	 'Antigua and Barbuda' , 
	 'Argentina' , 
	 'Armenia' , 
	 'Aruba' , 
	 'Australia' , 
	 'Austria' , 
	 'Azerbaijan' , 
	 'Bahamas' , 
	 'Bahrain' , 
	 'Bangladesh' , 
	 'Barbados' , 
	 'Belarus' , 
	 'Belgium' , 
	 'Belize' , 
	 'Benin' , 
	 'Bermuda' , 
	 'Bhutan' , 
	 'Bolivia' , 
	 'Bosnia and Herzegovina' , 
	 'Botswana' , 
	 'Brazil' , 
	 'Brunei Darussalam' , 
	 'Bulgaria' , 
	 'Burkina Faso' , 
	 'Burundi' , 
	 'Cambodia' , 
	 'Cameroon' , 
	 'Canada' , 
	 'Cape Verde' , 
	 'Cayman Islands' , 
	 'Central African Republic' , 
	 'Chad' , 
	 'Chile' , 
	 'China' , 
	 'Christmas Island' , 
	 'Cocos (Keeling) Islands' , 
	 'Colombia' , 
	 'Comoros' , 
	 'Congo, Republic of(Brazzaville)' , 
	 'Cook Islands' , 
	 'Costa Rica' , 
	 'Croatia' , 
	 'Cuba' , 
	 'Cyprus' , 
	 'Czech Republic' , 
	 'Democratic Republic of the Congo (Kinshasa)' , 
	 'Denmark' , 
	 'Djibouti' , 
	 'Dominica' , 
	 'Dominican Republic' , 
	 'East Timor (Timor-Leste)' , 
	 'Ecuador' , 
	 'Egypt' , 
	 'El Salvador' , 
	 'Equatorial Guinea' , 
	 'Eritrea' , 
	 'Estonia' , 
	 'Ethiopia' , 
	 'Falkland Islands' , 
	 'Faroe Islands' , 
	 'Fiji' , 
	 'Finland' , 
	 'France' , 
	 'French Guiana' , 
	 'French Polynesia' , 
	 'French Southern Territories' , 
	 'Gabon' , 
	 'Gambia' , 
	 'Georgia' , 
	 'Germany' , 
	 'Ghana' , 
	 'Gibraltar' , 
	 'Great Britain' , 
	 'Greece' , 
	 'Greenland' , 
	 'Grenada' , 
	 'Guadeloupe' , 
	 'Guam' , 
	 'Guatemala' , 
	 'Guinea' , 
	 'Guinea-Bissau' , 
	 'Guyana' , 
	 'Haiti' , 
	 'Holy See' , 
	 'Honduras' , 
	 'Hong Kong' , 
	 'Hungary' , 
	 'Iceland' , 
	 'India' , 
	 'Indonesia' , 
	 'Iran (Islamic Republic of)' , 
	 'Iraq' , 
	 'Ireland' , 
	 'Israel' , 
	 'Italy' , 
	 'Ivory Coast' , 
	 'Jamaica' , 
	 'Japan' , 
	 'Jordan' , 
	 'Kazakhstan' , 
	 'Kiribati' , 
	 'Korea, Democratic Peoples Rep. (North Korea)' , 
	 'Korea, Republic of (South Korea)' , 
	 'Kosovo' , 
	 'Kuwait' , 
	 'Kyrgyzstan' , 
	 'Lao, Peoples Democratic Republic' , 
	 'Latvia' , 
	 'Lebanon' , 
	 'Lesotho' , 
	 'Liberia' , 
	 'Libya' , 
	 'Liechtenstein' , 
	 'Lithuania' , 
	 'Luxembourg' , 
	 'Macau' , 
	 'Macedonia, Rep. of' , 
	 'Madagascar' , 
	 'Malawi' , 
	 'Malaysia' , 
	 'Maldives' , 
	 'Mali' , 
	 'Malta' , 
	 'Marshall Islands' , 
	 'Martinique' , 
	 'Mauritania' , 
	 'Mauritius' , 
	 'Mayotte' , 
	 'Mexico' , 
	 'Micronesia, Federal States of' , 
	 'Moldova, Republic of' , 
	 'Monaco' , 
	 'Mongolia' , 
	 'Montenegro' , 
	 'Montserrat' , 
	 'Morocco' , 
	 'Mozambique' , 
	 'Myanmar, Burma' , 
	 'Namibia' , 
	 'Nauru' , 
	 'Nepal' , 
	 'Netherlands' , 
	 'Netherlands Antilles' , 
	 'New Caledonia' , 
	 'New Zealand' , 
	 'Nicaragua' , 
	 'Niger' , 
	 'Nigeria' , 
	 'Niue' , 
	 'Northern Mariana Islands' , 
	 'Norway' , 
	 'Oman' , 
	 'Pakistan' , 
	 'Palau' , 
	 'Palestinian territories' , 
	 'Panama' , 
	 'Papua New Guinea' , 
	 'Paraguay' , 
	 'Peru' , 
	 'Philippines' , 
	 'Pitcairn Island' , 
	 'Poland' , 
	 'Portugal' , 
	 'Puerto Rico' , 
	 'Qatar' , 
	 'Reunion Island' , 
	 'Romania' , 
	 'Russian Federation' , 
	 'Rwanda' , 
	 'Saint Kitts and Nevis' , 
	 'Saint Lucia' , 
	 'Saint Vincent and the Grenadines' , 
	 'Samoa' , 
	 'San Marino' , 
	 'Sao Tome and Principe' , 
	 'Saudi Arabia' , 
	 'Senegal' , 
	 'Serbia' , 
	 'Seychelles' , 
	 'Sierra Leone' , 
	 'Singapore' , 
	 'Slovakia (Slovak Republic)' , 
	 'Slovenia' , 
	 'Solomon Islands' , 
	 'Somalia' , 
	 'South Africa' , 
	 'South Sudan' , 
	 'Spain' , 
	 'Sri Lanka' , 
	 'Sudan' , 
	 'Suri' , 
	 'Swaziland' , 
	 'Sweden' , 
	 'Switzerland' , 
	 'Syria, Syrian Arab Republic' , 
	 'Taiwan (Republic of China)' , 
	 'Tajikistan' , 
	 'Tanzania; officially the United Republic of Tanzania' , 
	 'Thailand' , 
	 'Tibet' , 
	 'Timor-Leste (East Timor)' , 
	 'Togo' , 
	 'Tokelau' , 
	 'Tonga' , 
	 'Trinidad and Tobago' , 
	 'Tunisia' , 
	 'Turkey' , 
	 'Turkmenistan' , 
	 'Turks and Caicos Islands' , 
	 'Tuvalu' , 
	 'Uganda' , 
	 'Ukraine' , 
	 'United Arab Emirates' , 
	 'United Kingdom' , 
	 'United States' , 
	 'Uruguay' , 
	 'Uzbekistan' , 
	 'Vanuatu' , 
	 'Vatican City State (Holy See)' , 
	 'Venezuela' , 
	 'Vietnam' , 
	 'Virgin Islands (British)' , 
	 'Virgin Islands (U.S.)' , 
	 'Wallis and Futuna Islands' , 
	 'Western Sahara' , 
	 'Yemen' , 
	 'Zambia' , 
	 'Zimbabwe' ];

App.prototype.business_categories = [
      '',
      'Automotive',
      'Business Support and Supplies',
      'Computers and Electronics',
      'Construction and Contractors',
      'Education',
      'Entertainment',
      'Food and Dining',
      'Financial Services',
      'Health and Medicine',
      'Home and Garden',
      'Legal Services',
      'Manufacturing, Wholesale,Distribution',
      'Merchants(Retail)',
      'Personal Care and Services',
      'Real Estate',
      'Travel and Transportation',
      'Other'
      ];


App.prototype.times = [
    "00:00", "01:00", "02:00", "03:00",
    "04:00", "05:00", "06:00", "07:00",
    "08:00", "09:00", "10:00", "11:00",
    "12:00", "13:00", "14:00", "15:00",
    "16:00", "17:00", "18:00", "19:00",
    "20:00", "21:00", "22:00", "23:00", "23:59"
];